name: publish

on:
  release:
    types:
      - prereleased
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: poetry install --no-root
      - run: poetry build
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN_ORGANIZATION }}"
      - run: poetry publish
